import { readFile, writeFile } from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const read=p=>readFile(new URL(p,root),'utf8');
const [template,css,core,blocks,runtime]=await Promise.all(['engine-src/template.html','engine-src/theme.css','engine-src/core.mjs','engine-src/blocks.js','engine-src/runtime.js'].map(read));
const html=template.replace('/*STYLE*/',()=>css).replace('/*SCRIPT*/',()=>core.replace(/^export /gm,'')+'\n'+blocks+'\n'+runtime);
await writeFile(new URL('public/engines.html',root),html);
await writeFile(new URL('app/api/download/template.ts',root),'// Generated by assemble-engines.mjs.\nexport const engineHTML = '+JSON.stringify(html)+';\n');
console.log('Assembled 12 self-contained teaching engines.');
